<a href="https://colab.research.google.com/github/jyeongvv/DataAnalysis_jy/blob/main/jyeongvv/ch05_01%2B02_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # 규칙

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
np.array((1, 2, 3))

array([1, 2, 3])

In [6]:
np.array(range(1, 4))

array([1, 2, 3])

In [10]:
np.array([int(c) for c in "123"])

array([1, 2, 3])

In [12]:
arr = np.array([1, 2, 3])

In [14]:
type(arr) # ndarray -> n개의 차원을 가진...

numpy.ndarray

## 벡터화 연산

In [16]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
a + [10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
a * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
[v for v in a]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
[v + 2 for v in a]

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [25]:
[v * 2 for v in a]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
arr = np.arange(10) # np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr + 2 # 배열(np.ndarray)에서 산술 연산자는 각각의 원소들에 대해서 계산 진행

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.ones_like(arr) * 2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
arr + np.ones_like(arr) * 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
(((arr * 5) // 2) - 1) % 7

array([6, 1, 4, 6, 2, 4, 0, 2, 5, 0])

In [35]:
arr == 5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [36]:
arr[arr == 5]

array([5])

In [37]:
arr[arr > 5]

array([6, 7, 8, 9])

In [38]:
np.where(arr > 5)

(array([6, 7, 8, 9]),)

In [40]:
arr2 = np.arange(6, 25, 2)
arr2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [42]:
np.where(arr2 % 3 == 0)

(array([0, 3, 6, 9]),)

In [44]:
arr2[np.where(arr2 % 3 == 0)] # arr2[arr2 % 3 == 0]

array([ 6, 12, 18, 24])

In [46]:
arr2[[0] * 5]

array([6, 6, 6, 6, 6])

In [48]:
(arr > 5) | (arr % 2 == 0)

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True])

In [49]:
arr[(arr > 5) | (arr % 2 == 0)]

array([0, 2, 4, 6, 7, 8, 9])

In [51]:
arr[(arr > 5) & (arr % 2 == 0)]

array([6, 8])

In [53]:
# ndarray
np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [54]:
np.array([[1, 2, 3, 4], [1, 2, 3]]) # 행들 간의 길이(열의 크기) 같아야함

<ipython-input-54-e6426570ace6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3, 4], [1, 2, 3]])


array([list([1, 2, 3, 4]), list([1, 2, 3])], dtype=object)

In [55]:
a1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
a1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [56]:
a1[1, 1]

2

In [57]:
a2 = np.array([[1, 2, 3, 4], [1, 2, 3]])
a2[1, 1]

<ipython-input-57-b813f9fe8871>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[1, 2, 3, 4], [1, 2, 3]])


IndexError: ignored

In [58]:
a1.ndim, a1.shape

(2, (2, 4))

In [60]:
a2.ndim, a2.shape

(1, (2,))

In [62]:
m = np.array([[1, 2], [3, 4]])
m2 = np.array([range(2, 4), range(1, 3)])
print(m)
print(m2)

[[1 2]
 [3 4]]
[[2 3]
 [1 2]]


In [64]:
t = np.array([
    [
        [1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]
    ],
    [
        [1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]
    ],
])
t

array([[[1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]],

       [[1, 4, 5, 6],
        [1, 4, 5, 6],
        [1, 4, 5, 6]]])

In [65]:
t.ndim, t.shape

(3, (2, 3, 4))

In [87]:
a = np.arange(10).reshape((5, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [88]:
b = a
b[0, 1] = 9

In [89]:
print(a)
print(b)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [90]:
c= a.copy()
c[2, 1] = -99
print(a)
print(c)

[[0 9]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[  0   9]
 [  2   3]
 [  4 -99]
 [  6   7]
 [  8   9]]


In [91]:
a = np.arange(1, 100, 25)
a

array([ 1, 26, 51, 76])

In [92]:
a[3], a[-1], a[len(a)-1], a[a.shape[0]-1]

(76, 76, 76, 76)

In [93]:
# , [] []
m = np.arange(6).reshape((2, 3))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [97]:
m[0, 0], m[0, 1]

(0, 1)

In [100]:
m.ndim, m.shape

(2, (2, 3))

In [101]:
m[-2, 0], m[-2, -1]

(0, 2)

In [102]:
m[m.shape[0]-2, 0], m[m.shape[0]-2, m.shape[1]-1]

(0, 2)

In [107]:
d1, d2 = m.shape # d1 : 행차원의 길이, d2 : 열차원의 길이
row_length, colimn_length = m.shape

In [109]:
m[d1-2, 0], m[d1-2, d2-1]
m[row_length-2, 0], m[row_length-2, colimn_length-1]

(0, 2)

In [112]:
#  1차원의 배열의 슬라이싱 = 리스트의 슬라이싱과 같음
a[1:2]

array([26])

In [113]:
a2 = np.arange(0, 100, 10)
a2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [117]:
a2[1:10:2], a2[10::-1], a2[::-1], a2[:]

(array([10, 30, 50, 70, 90]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [119]:
  m

array([[0, 1, 2],
       [3, 4, 5]])

In [120]:
m[0,:], m[0]

(array([0, 1, 2]), array([0, 1, 2]))

In [122]:
m[:,0]
print(m[:,0:1])

[[0]
 [3]]


## 배열의 자료형

In [154]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [155]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [156]:
x = np.array([1, 2.0, 3])
x.dtype

dtype('float64')

In [157]:
x = np.array([1, 2.0, "3"])
x.dtype

dtype('<U32')

In [158]:
x = np.array([1, 2, 3], dtype='i')
x2 = np.array([1, 2, 3], dtype=int)
print(x, x.dtype)
print(x2, x2.dtype)

[1 2 3] int32
[1 2 3] int64


In [159]:
x = np.array([1, 2, 3], dtype='f')
x2 = np.array([1, 2, 3], dtype=float)
print(x, x.dtype)
print(x2, x2.dtype)

[1. 2. 3.] float32
[1. 2. 3.] float64


In [160]:
x = np.array([1, 2, 3.5], dtype='i')
print(x, x.dtype)

[1 2 3] int32


In [161]:
x = np.array([1, 2, "안녕"], dtype='i')
print(x, x.dtype)

ValueError: ignored

In [162]:
a = np.zeros(5)
b = np.array([0, 1, 0, 1, 0]) # 0 / 0 -> nan not a number. -> na.
a / b, b / a

<ipython-input-162-938594f7caf7>:3: RuntimeWarning: invalid value encountered in true_divide
  a / b, b / a
<ipython-input-162-938594f7caf7>:3: RuntimeWarning: divide by zero encountered in true_divide
  a / b, b / a


(array([nan,  0., nan,  0., nan]), array([nan, inf, nan, inf, nan]))

In [163]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [164]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [165]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [166]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [167]:
np.ones_like(a)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [168]:
np.empty((2, 5))

array([[2.66683039e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.90327671e-310],
       [5.29171122e+174, 3.88601444e-033, 7.73063390e-091,
        6.10110133e+170, 4.57620884e-315]])

In [169]:
np.linspace(10, 100, 5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [170]:
np.logspace(0.1, 1, 5)

array([ 1.25892541,  2.11348904,  3.54813389,  5.95662144, 10.        ])

In [171]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
A.ndim, A.shape

(2, (2, 3))

In [173]:
A2 = A.T
A2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [174]:
A2.ndim, A2.shape

(2, (3, 2))

In [176]:
A, A.flatten(), A.ravel()

(array([[1, 2, 3],
        [4, 5, 6]]), array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 4, 5, 6]))

In [177]:
t = np.arange(30).reshape(3, 5, 2)
t

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [178]:
t.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [180]:
x = np.arange(5)
print(x, x.ndim, x.shape)
x2 = x[:, np.newaxis]
print(x2, x2.ndim, x2.shape)
x3 = x[np.newaxis, :]
print(x3, x3.ndim, x3.shape)

[0 1 2 3 4] 1 (5,)
[[0]
 [1]
 [2]
 [3]
 [4]] 2 (5, 1)
[[0 1 2 3 4]] 2 (1, 5)
