<a href="https://colab.research.google.com/github/jyeongvv/DataAnalysis_jy/blob/main/jyeongvv/ch05_02%2B03%2B04_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01

In [1]:
import numpy as np

In [3]:
arr1 = np.arange(1, 4)
arr2 = np.arange(4, 7)
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [5]:
np.concatenate([arr1, arr2, arr1])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [8]:
arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

np.concatenate([arr1, arr2])
np.concatenate([arr1, arr2], axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [12]:
np.concatenate([arr1, arr2], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [19]:
# b1 = np.ones((2, 3))
b1 = np.ones_like(a1)
b2 = np.zeros((3, 3))
np.vstack((b1, b2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
c1 = np.ones((3, 4))
c2 = np.zeros_like(c1)
np.dstack((c1, c2)) # 행, 열 길이가 같아야하고, 가장 마지막(안쪽의) 차원이 1증가하면서 합쳐짐

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [23]:
# c = np.stack([c1, c2])
c = np.stack([c1, c2], axis=0) # 행기준
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
np.stack([c1, c2], axis=1) # 열기준

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [25]:
np.stack([c1, c2], axis=-1) # 차원을 추가하면서 합쳐짐 (dstack)

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [26]:
# r_ -> hstack. 1,2,3 / 4,5,6
np.r_[np.arange(1, 4), np.arange(4, 7)]

array([1, 2, 3, 4, 5, 6])

In [27]:
np.r_[np.arange(1, 4), np.arange(4, 7), np.arange(4, 7)]

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [28]:
np.c_[np.arange(1, 4), np.arange(4, 7)]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
np.concatenate((np.arange(1, 4)[:, np.newaxis], np.arange(4, 7)[:, np.newaxis]), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
a = np.arange(6).reshape(3, -1)
print(np.tile(a, 3)) # 모양을 지키면서 반복
print(np.repeat(a, 3)) # flattern 시킨 다음에, 각 원소들을 그 위치에 반복

[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [4 5 4 5 4 5]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [35]:
arr = np.arange(7)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
np.array_split(arr, 3) # array_split -> 되는대로 3등분

[array([0, 1]), array([2, 3]), array([4, 5])]

In [40]:
arr = np.arange(6)
np.split(arr, 3) # split -> 엄격하게 약수로 맞게 입력해야 쪼개준다ㅏ

[array([0, 1]), array([2, 3]), array([4, 5])]

In [41]:
arr = np.arange(1, 19).reshape(-1, 3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [46]:
# np.array_split(arr, 3)
np.array_split(arr, 3, axis=0) # 행 방향으로

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]])]

In [47]:
np.array_split(arr, 3, axis=1) # 열 방향으로

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

## 02


In [48]:
# 브로드캐스팅 : 크기가 작은 배열을 자동으로 반복확장하여 크기가 큰 배열에 맞추는 방법
x = np.arange(5)
x + 1

array([1, 2, 3, 4, 5])

In [49]:
x + np.ones_like(x) * 1

array([1, 2, 3, 4, 5])

In [50]:
x + 10

array([10, 11, 12, 13, 14])

In [52]:
np.ones_like(x) * 10

array([10, 10, 10, 10, 10])

In [53]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [55]:
y = np.arange(5).reshape(-1, 1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [57]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [60]:
x = np.arange(1, 5)

In [63]:
np.sum(x), x.sum()

(10, 10)

In [64]:
x.min(), x.max()

(1, 4)

In [66]:
x.argmin(), x.argmax()

(0, 3)

In [67]:
x.mean()

2.5

In [68]:
np.median(x)

2.5

In [70]:
np.any(x > 4), np.any(x > 2)

(False, True)

In [74]:
np.all(x > 4), np.all(x > 2), np.all(x >= 0)

(False, False, True)

In [76]:
x = np.array(((1, 1), (2, 2)))
x

array([[1, 1],
       [2, 2]])

In [78]:
x.sum()

6

In [80]:
x.sum(axis=0) # 행 내부에 있는 열들간의 연산, 행의 대푯값 (axis=0)

array([3, 3])

In [81]:
x.sum(axis=1) # 열 내부에 있는 행들간의 연산, 열의 대푯값 (axis=1)

array([2, 4])

In [84]:
a = np.random.randint(1, 20, 12).reshape(3, -1)
a

array([[ 2,  2,  5, 11],
       [12, 17,  7, 15],
       [ 7, 12,  6, 19]])

In [85]:
np.sort(a)
np.sort(a, axis=1)

array([[ 2,  2,  5, 11],
       [ 7, 12, 15, 17],
       [ 6,  7, 12, 19]])

In [86]:
a.sort(axis=1) # 원본 변경이 아닌 사본 생성

In [87]:
a

array([[ 2,  2,  5, 11],
       [ 7, 12, 15, 17],
       [ 6,  7, 12, 19]])

In [89]:
np.argsort(a)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [91]:
np.argsort(a, axis=0)

array([[0, 0, 0, 0],
       [2, 2, 2, 1],
       [1, 1, 1, 2]])

In [92]:
x = np.random.randint(0, 100, 12).reshape(3, -1)
x

array([[91, 35, 26,  5],
       [22, 62, 38, 31],
       [77, 19, 97, 78]])

In [96]:
x[:, np.argsort(x[1])]

array([[91,  5, 26, 35],
       [22, 31, 38, 62],
       [77, 78, 97, 19]])

In [97]:
x = np.random.randint(-30, 30, 30)
x

array([-26, -20,  10,  21, -23,  25,  24, -18,   9,  -6,  -9,  26,  16,
        17,  19,  12, -29, -14, -25,  29,  -1,  20, -15,   4,  -5, -12,
       -26,  11,  27,  13])

In [98]:
len(x)

30

In [100]:
np.mean(x), x.mean()

(1.8, 1.8)

In [101]:
np.var(x)

350.2266666666667

In [104]:
np.std(x), x.std()

(18.714343874864188, 18.714343874864188)

In [103]:
np.max(x), np.min(x)

(29, -29)

In [106]:
np.median(x) # 짝수개일 경우, 두 값의 평균을 쓴다

6.5

In [109]:
np.quantile(x, 0), np.percentile(x, 0) # 최솟값

(-29, -29.0)

In [110]:
# 사분위수 => 1을 최대로 봤을 때의 비율스, 1/4, 2/4, 3/4...
# 백분위수는 100을 최대로 봤을 때의 값을 입력
np.quantile(x, 0.25), np.percentile(x, 25) # 1사분위수, 25백분위수

(-14.75, -14.75)

In [111]:
np.quantile(x, 2/4), np.percentile(x, 50) # 2사분위수, 50백분위수, 중앙값

(6.5, 6.5)

In [ ]:
np.quantile(x, 3/4), np.percentile(x, 75) # 3사분위수, 35백분위수

In [112]:
np.quantile(x, 4/4), np.percentile(x, 100) # 최댓값

(29.0, 29.0)

In [114]:
# np.random.seed(0) # 이후 나오는 랜덤값들이 순서가 일치
np.random.seed(0)

In [115]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [117]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.random.shuffle(x)

In [119]:
x

array([3, 1, 8, 7, 9, 0, 6, 4, 2, 5])

In [120]:
 np.random.choice(x, 5, replace=False) # x 배열 안의 있는 값 중에 5개를 추출(비복원)

array([0, 8, 7, 9, 1])

In [121]:
np.random.choice(5, 5, replace=False)

array([2, 3, 4, 1, 0])

In [123]:
np.random.choice(np.arange(1, 46), 6, replace=False)

array([39, 37, 26,  9, 20, 23])

In [126]:
np.random.choice(np.arange(1, 7), 6)
np.random.choice(np.arange(1, 7), 6, replace=True)

array([3, 4, 5, 2, 3, 4])

In [127]:
np.random.choice(np.arange(1, 7), 6, p=[0, 0, 0, 0.6, 0.2, 0.2])

array([6, 6, 4, 4, 4, 6])

In [128]:
np.random.randn(10) # 0이 평균, 표준편차 -1, -2.+2 => 99.9% 0 에 가까울 수록 값들이 더 많이 등장

array([ 0.99982969,  0.43103415, -0.65091287, -1.49874039, -1.23063497,
        0.19400719, -0.99838235, -0.3676376 ,  1.73719932,  0.59361275])

In [129]:
np.random.randn(3, 5)

array([[-0.54236358, -1.71967238, -0.57890879,  1.42694855,  0.27699691],
       [ 0.78966713,  0.32207411,  0.70039238,  0.38871663, -0.04126386],
       [ 0.29588432, -0.42527999,  1.72763912, -0.86835257, -0.82097758]])

In [130]:
np.random.randint(10) # 최소 0, low

9

In [131]:
np.random.randint(1, 10) # 최소 low, 최대 high

1

In [132]:
np.random.randint(1, 10, 100) # 최소 low, 최대 high, size

array([7, 6, 4, 2, 9, 1, 5, 7, 6, 8, 9, 9, 3, 9, 7, 7, 2, 7, 9, 9, 4, 3,
       4, 7, 4, 7, 6, 8, 1, 9, 5, 7, 6, 9, 3, 4, 8, 6, 4, 5, 6, 4, 4, 8,
       8, 4, 3, 4, 8, 8, 6, 2, 3, 3, 9, 2, 6, 9, 5, 1, 3, 6, 6, 1, 9, 2,
       2, 1, 4, 9, 9, 5, 5, 1, 4, 8, 4, 3, 2, 2, 3, 2, 5, 3, 6, 6, 6, 3,
       6, 8, 8, 7, 2, 7, 8, 3, 4, 2, 6, 3])

In [134]:
# 가격이 1만원 주식
price = 10000
# 일간 수익률 -> 기댓값 0, 표준편차 1$=0.01 (표준정규분포)
days = 250
daily_earning_rate = np.random.randn(days) / 100
print(daily_earning_rate)
# 250일 동안의 주가를 무작위로 생성
# 주가 -> 전일 가격 * (1 + 당일 수익률)
price_arr = np.empty(days)
for i, v, in enumerate(daily_earning_rate):
    print(v)
    price *= (1 + v)
    print(price)
    price_arr[i] = price
    print(price_arr[1])
price_arr

[-9.67497398e-03  1.06825969e-02  1.21308761e-02  1.14471880e-02
  1.67840445e-02  4.78404880e-03  9.17376518e-04  4.26534769e-04
  1.36425174e-02  1.09958891e-02 -6.27734441e-03 -1.29316820e-03
 -8.98539413e-03  1.93064772e-02  1.98606513e-03 -1.45807253e-03
 -2.19114451e-03  1.76249777e-02 -1.28223947e-02  2.69826794e-03
  8.78698596e-03  7.96627365e-05  1.08857292e-02  7.89783026e-04
  8.06082332e-03  5.19104919e-03 -1.27284450e-03 -8.40984011e-03
 -4.95306201e-03 -1.37020005e-03  9.87424495e-03 -7.18549682e-03
  1.93803498e-02  2.20391311e-03 -4.75094890e-03  2.38653989e-03
  4.05642436e-03  2.99658730e-03  6.91165041e-03 -1.90583721e-02
  2.82044327e-03 -2.28763993e-02 -5.51474125e-03  1.20762067e-02
 -1.15179807e-02  1.55182596e-03 -6.32009056e-03 -1.81677267e-02
 -1.88014899e-03  8.90667144e-04 -1.60539390e-02 -7.07515588e-03
 -2.14910446e-02  1.26303753e-03 -4.36291006e-04  1.01271502e-02
 -1.74233712e-02 -1.06847438e-02  1.65534940e-02  8.51931977e-03
  1.37098216e-02  2.74074

array([ 9903.25026018, 10009.04269073, 10130.4611471 , 10246.42644062,
       10418.40291783, 10468.24506579, 10477.84838799, 10482.31755463,
       10625.32275397, 10742.15762415, 10674.72540102, 10660.9211856 ,
       10565.12860699, 10769.10402148, 10790.49216347, 10774.7588433 ,
       10751.1497896 , 10940.63856492, 10800.35337935, 10829.49562667,
       10924.65425268, 10925.52454053, 11044.45684195, 11053.1795665 ,
       11142.27729409, 11200.11740361, 11185.8613958 , 11091.79008998,
       11036.85176588, 11021.72907106, 11130.56032369, 11050.5817179 ,
       11264.74585716, 11289.57237823, 11235.93619671, 11262.75120667,
       11308.43770504, 11342.32442581, 11420.7186071 , 11203.05830248,
       11234.65589286, 10977.64741911, 10917.10853404, 11048.94579272,
       10921.68424876, 10938.63280189, 10869.49965195, 10672.02555333,
       10651.96055526, 10661.44790654, 10490.28967195, 10416.06923735,
       10192.21702919, 10205.09018183, 10200.63779278, 10303.94118371,
      

In [135]:
np.random.randint(1, 10, 100)
x

array([3, 1, 8, 7, 9, 0, 6, 4, 2, 5])

In [136]:
np.unique(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.unique(x, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [140]:
np.unique(x, return_counts=True, return_index=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([5, 1, 8, 0, 7, 9, 6, 3, 2, 4]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [141]:
key, value = np.unique(x, return_counts=True)
print(key)
print(value)

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1 1 1]


In [142]:
# 2개의 시퀀스를, 인덱스로 묶어줌 zip
list(zip(key, value))

[(0, 1),
 (1, 1),
 (2, 1),
 (3, 1),
 (4, 1),
 (5, 1),
 (6, 1),
 (7, 1),
 (8, 1),
 (9, 1)]

In [144]:
dict(zip(key, value))

{0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}

In [145]:
x = np.random.randint(30, size=10)
x

array([ 3,  7,  1,  1,  7, 25,  4, 13, 12, 18])

In [147]:
np.bincount(x, minlength=30)

array([0, 2, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0])

In [149]:
np.arange(30), np.bincount(x, minlength=30)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]),
 array([0, 2, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0]))

In [150]:
dict(zip(np.arange(30), np.bincount(x, minlength=30)))

{0: 0,
 1: 2,
 2: 0,
 3: 1,
 4: 1,
 5: 0,
 6: 0,
 7: 2,
 8: 0,
 9: 0,
 10: 0,
 11: 0,
 12: 1,
 13: 1,
 14: 0,
 15: 0,
 16: 0,
 17: 0,
 18: 1,
 19: 0,
 20: 0,
 21: 0,
 22: 0,
 23: 0,
 24: 0,
 25: 1,
 26: 0,
 27: 0,
 28: 0,
 29: 0}